// SPDX-License-Identifier: GPL-2.0-only

// Command mcpfillet drives the LIVE oblikovati app over the MCP bridge to exercise a matrix of
// fillet (edge-round) CORNER configurations and capture each result — the repeatable "look at the
// corners" loop behind the fillet corner-quality work, mirroring the chamfer driver (mcpchamfer).
//
// For each configuration it builds a fresh box, selects an edge set that forms a particular kind
// of corner, applies the fillet(s), frames the +X+Y+Z corner, and writes a window PNG to --dir:
//
//	01 single edge (vertical)                   05 variable radius (start→end over one edge)
//	02 three-edge box corner (symmetric)        06 L-pair (two-edge corner)
//	03 four-edge top loop (two-edge corners)    07 fillet-of-fillet: miter edge (4-edge vertex)
//	04 whole box (all corners blend)            08 fillet-of-fillet: corner edge (flush, no lip)
//
// Cases 07/08 fillet an edge GENERATED by a first fillet — they verify the second fillet blends
// flush (no lip remnants or sliver spikes) where it dies into a vertex. With PROBE=1 it also logs
// edge-count/volume deltas and writes per-triangle and wide shots. With DUMP=1 it prints one box's
// edge midpoints.
//
// Usage: mcpfillet [--url http://127.0.0.1:7800/mcp] [--dir /tmp/fillet]
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"math"
	"os"
	"sort"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

func main() {
	url := flag.String("url", "http://127.0.0.1:7800/mcp", "MCP endpoint URL")
	dir := flag.String("dir", "/tmp/fillet", "directory for the captured PNGs")
	flag.Parse()
	if err := os.MkdirAll(*dir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mcpfillet:", err)
		os.Exit(1)
	}
	if err := run(*url, *dir); err != nil {
		fmt.Fprintln(os.Stderr, "mcpfillet:", err)
		os.Exit(1)
	}
}

type ref struct {
	key string
	p   [3]float64
}

type driver struct {
	ctx context.Context
	cs  *mcp.ClientSession
	dir string
	seq int
}

func run(url, dir string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()
	cl := mcp.NewClient(&mcp.Implementation{Name: "mcpfillet", Version: "0.1.0"}, nil)
	cs, err := cl.Connect(ctx, &mcp.StreamableClientTransport{Endpoint: url}, nil)
	if err != nil {
		return fmt.Errorf("connect %s: %w", url, err)
	}
	defer cs.Close()
	d := &driver{ctx: ctx, cs: cs, dir: dir}
	d.call("close_all_documents", map[string]any{"force": true}) // start from an empty session (no cross-run doc-name collisions)

	if os.Getenv("DUMP") != "" {
		edges := d.freshBox()
		fmt.Printf("EDGES=%d\n", len(edges))
		for i, e := range edges {
			fmt.Printf("edge %2d  mid=(% .3f % .3f % .3f)\n", i, e.p[0], e.p[1], e.p[2])
		}
		return nil
	}

	// Each scenario: a label, the edge selector, and the fillet args (minus edgeRefs).
	d.scenario("01-single-edge", d.vertEdge, radius("3 mm"))
	d.scenario("02-corner3-sym", d.cornerEdges, radius("3 mm"))
	d.scenario("03-toploop4", d.topEdges, radius("3 mm"))
	d.scenario("04-wholebox12", d.allEdges, radius("3 mm"))
	d.scenarioVariable("05-variable-edge")
	d.scenario("06-Lpair2", d.twoEdgeL, radius("3 mm"))
	d.scenarioMiterRefillet("07-refillet-miter-edge")
	d.scenarioSingleEdgeRefillet("08-refillet-corner-edge")
	return nil
}

// radius builds a constant-radius fillet arg block.
func radius(r string) map[string]any { return map[string]any{"radius": r} }

// scenario builds a fresh box, applies the fillet to the selected edges, frames the +X+Y+Z
// corner, and captures the window.
func (d *driver) scenario(label string, pick func([]ref) []ref, fillet map[string]any) {
	sel := pick(d.freshBox())
	status := d.fillet(sel, fillet)
	d.captureCorner(label, fmt.Sprintf("edges=%2d %s", len(sel), status))
}

// scenarioVariable rounds the single vertical edge at V with a radius that grows from 1 mm at one
// end to 6 mm at the other — the variable-radius edge-set form, which only the fillet (not the
// chamfer) supports.
func (d *driver) scenarioVariable(label string) {
	sel := d.vertEdge(d.freshBox())
	status := d.filletSets([]map[string]any{
		{"edgeRefs": keysOf(sel), "startRadius": "1 mm", "endRadius": "6 mm"},
	})
	d.captureCorner(label, "variable "+status)
}

// scenarioMiterRefillet rounds the four top edges — which turns each top-corner VERTEX into a
// rounded saddle where the two adjacent top fillets meet — then fillets the new edge at the
// +X+Y+Z corner. The second fillet references topology that did not exist before the first
// feature ran, exercising the re-pick of a freshly created edge.
func (d *driver) scenarioMiterRefillet(label string) {
	d.fillet(d.topEdges(d.freshBox()), radius("3 mm")) // first fillet: each top corner vertex → a curved seam
	corner := nearestEdge(d.edges(), [3]float64{xMax, yMax, zTop})
	if corner == nil {
		d.captureCorner(label, "no new edge found")
		return
	}
	d.refilletAndEvaluate(label, *corner)
}

// scenarioSingleEdgeRefillet rounds ONE edge (the vertical edge at (4,3)), then fillets one of the
// short "corner edges" the first fillet generated at the strip end (near (4,3,2)) — that edge dies
// into a 3-edge vertex, simpler than the miter case's 4-edge vertex, so it isolates whether any
// sliver is specific to the complex-vertex topology.
func (d *driver) scenarioSingleEdgeRefillet(label string) {
	box := d.freshBox()
	vert := filter(box, func(r ref) bool { return near(r.p[0], xMax) && near(r.p[1], yMax) }) // the (4,3) vertical edge
	d.fillet(vert, radius("3 mm"))
	corner := nearestEdge(d.edges(), [3]float64{xMax, yMax, zTop}) // a generated corner edge of the fillet strip
	if corner == nil {
		d.captureCorner(label, "no corner edge found")
		return
	}
	d.refilletAndEvaluate(label, *corner)
}

// refilletAndEvaluate applies a 1 mm second fillet to edge, captures the corner (plus a wide shot
// and a tight per-triangle shot under PROBE), and logs the edge-count and volume deltas so a gouge
// (large volume drop) is distinguishable from a clean round (tiny drop).
func (d *driver) refilletAndEvaluate(label string, edge ref) {
	beforeN, beforeV := len(d.edges()), d.volume()
	status := d.fillet([]ref{edge}, radius("1 mm"))
	if os.Getenv("PROBE") != "" {
		fmt.Printf("  [probe] %-26s edge mid=(% .2f % .2f % .2f); edges %d→%d, vol %.5f→%.5f (Δ%.5f); %s\n",
			label, edge.p[0], edge.p[1], edge.p[2], beforeN, len(d.edges()), beforeV, d.volume(), beforeV-d.volume(), status)
		fmt.Printf("  [probe]   faces nearest (4,3,2):\n")
		for _, f := range nearestFaces(d.faces(), [3]float64{xMax, yMax, zTop}, 8) {
			fmt.Printf("    %-8s ctr=(% .3f % .3f % .3f)\n", f.kind, f.p[0], f.p[1], f.p[2])
		}
		// set_camera must NOT be the last call before capture (the move lands a frame late), so the
		// set_mesh_colors call sits between them — mirroring captureCorner's working order.
		d.call("set_camera", map[string]any{"eye": []float64{4.5, 3.8, 2.6}, "target": []float64{4, 3, 2}, "up": []float64{0, 0, 1}, "fov": 0.5})
		d.call("set_mesh_colors", map[string]any{"on": true, "perTriangle": true})
		d.call("capture_window", map[string]any{"path": d.dir + "/" + label + "-tris.png"})
		d.call("set_camera", map[string]any{"eye": []float64{9, 8, 6}, "target": []float64{2, 1.5, 1}, "up": []float64{0, 0, 1}, "fov": 0.5})
		d.call("set_mesh_colors", map[string]any{"on": true, "perTriangle": false})
		d.call("capture_window", map[string]any{"path": d.dir + "/" + label + "-wide.png"})
	}
	d.captureCorner(label, "refillet "+status)
}

// volume reads the active part's volume (cm³) via get_physical_properties.
func (d *driver) volume() float64 {
	var pp struct {
		Volume float64 `json:"volume"`
	}
	d.callJSON("get_physical_properties", nil, &pp)
	return pp.Volume
}

// fillet applies one constant-radius fillet feature to the selected edges and returns a status.
func (d *driver) fillet(sel []ref, fillet map[string]any) string {
	fillet["edgeRefs"] = keysOf(sel)
	return d.addFillet(fillet)
}

// filletSets applies one edge-set fillet feature (mixed constant/variable radius) and returns a
// status. Each set is a raw map ({edgeRefs, radius} or {edgeRefs, startRadius, endRadius}).
func (d *driver) filletSets(sets []map[string]any) string {
	return d.addFillet(map[string]any{"edgeSets": sets})
}

func (d *driver) addFillet(args map[string]any) string {
	var r struct {
		Healthy bool   `json:"healthy"`
		Reason  string `json:"reason"`
	}
	d.callJSON("add_feature", map[string]any{"kind": "fillet", "args": args}, &r)
	if !r.Healthy {
		return "SICK: " + r.Reason
	}
	return "healthy"
}

// captureCorner frames TIGHTLY on the +X+Y+Z corner (vertex (4,3,2)) so the corner treatment fills
// the view, captures the window, and logs.
func (d *driver) captureCorner(label, note string) {
	d.call("set_camera", map[string]any{
		"eye": []float64{4.9, 4.1, 2.95}, "target": []float64{4, 3, 2}, "up": []float64{0, 0, 1}, "fov": 0.5,
	})
	d.call("set_mesh_colors", map[string]any{"on": true, "perTriangle": false}) // one colour per face → corner faces stand out
	out := d.dir + "/" + label + ".png"
	d.call("capture_window", map[string]any{"path": out})
	fmt.Printf("%-24s %-22s -> %s\n", label, note, out)
}

// freshBox creates a new part with one 40×30×20 mm box and returns its edge refs (with midpoints).
func (d *driver) freshBox() []ref {
	d.seq++
	d.call("create_document", map[string]any{"type": "part", "name": fmt.Sprintf("fillet-%d", d.seq)})
	d.call("create_sketch", map[string]any{"plane": "XY"})
	d.call("sketch_rectangle", map[string]any{"sketchIndex": 0, "width": "40 mm", "height": "30 mm"})
	d.callJSON("add_feature", map[string]any{"kind": "extrude",
		"args": map[string]any{"sketchIndex": 0, "profileIndex": 0, "distance": "20 mm", "operation": "new"}}, &struct{}{})
	return d.edges()
}

type faceRef struct {
	kind string
	p    [3]float64
}

// faces returns the active body's face refs (range-box centre + geometry kind).
func (d *driver) faces() []faceRef {
	var rk struct {
		Bodies []struct {
			Faces []struct {
				Kind  string    `json:"kind"`
				Point []float64 `json:"point"`
			} `json:"faces"`
		} `json:"bodies"`
	}
	if !d.callJSON("get_reference_keys", nil, &rk) || len(rk.Bodies) == 0 {
		return nil
	}
	out := make([]faceRef, 0, len(rk.Bodies[0].Faces))
	for _, f := range rk.Bodies[0].Faces {
		if len(f.Point) == 3 {
			out = append(out, faceRef{kind: f.Kind, p: [3]float64{f.Point[0], f.Point[1], f.Point[2]}})
		}
	}
	return out
}

// nearestFaces returns the n faces whose range-box centres are closest to target.
func nearestFaces(f []faceRef, target [3]float64, n int) []faceRef {
	cp := append([]faceRef{}, f...)
	dist := func(r faceRef) float64 {
		dx, dy, dz := r.p[0]-target[0], r.p[1]-target[1], r.p[2]-target[2]
		return dx*dx + dy*dy + dz*dz
	}
	sort.Slice(cp, func(i, j int) bool { return dist(cp[i]) < dist(cp[j]) })
	if len(cp) > n {
		cp = cp[:n]
	}
	return cp
}

// edges returns the active body's edge refs.
func (d *driver) edges() []ref {
	var rk struct {
		Bodies []struct {
			Edges []struct {
				Key   string    `json:"key"`
				Point []float64 `json:"point"`
			} `json:"edges"`
		} `json:"bodies"`
	}
	if !d.callJSON("get_reference_keys", nil, &rk) || len(rk.Bodies) == 0 {
		return nil
	}
	out := make([]ref, 0, len(rk.Bodies[0].Edges))
	for _, e := range rk.Bodies[0].Edges {
		if len(e.Point) == 3 {
			out = append(out, ref{key: e.Key, p: [3]float64{e.Point[0], e.Point[1], e.Point[2]}})
		}
	}
	return out
}

// keysOf extracts the reference keys from a slice of edge refs.
func keysOf(sel []ref) []string {
	keys := make([]string, len(sel))
	for i, e := range sel {
		keys[i] = e.key
	}
	return keys
}

// --- edge selectors (box is x∈[0,4], y∈[0,3], z∈[0,2] cm; the corner of interest is vertex
// V=(4,3,2), the +X+Y+Z box corner) -----------------------------------------------------------

const (
	xMax = 4.0
	yMax = 3.0
	zTop = 2.0
)

func near(a, b float64) bool { return math.Abs(a-b) < 1e-6 }

// the three edges meeting at V=(4,3,2):
func isTopX(r ref) bool { return near(r.p[1], yMax) && near(r.p[2], zTop) } // along X at y=3, mid (2,3,2)
func isTopY(r ref) bool { return near(r.p[0], xMax) && near(r.p[2], zTop) } // along Y at x=4, mid (4,1.5,2)
func isVert(r ref) bool { return near(r.p[0], xMax) && near(r.p[1], yMax) } // vertical at (4,3), mid (4,3,1)

// allEdges selects every edge (all 8 corners are three-edge corners).
func (d *driver) allEdges(e []ref) []ref { return e }

// vertEdge selects only the single vertical edge at V=(4,3).
func (d *driver) vertEdge(e []ref) []ref { return filter(e, isVert) }

// topEdges selects the four edges of the top face (z=zTop) — each of its corners is a meeting
// of only TWO selected edges, so the three-edge corner blend never fires there.
func (d *driver) topEdges(e []ref) []ref {
	return filter(e, func(r ref) bool { return near(r.p[2], zTop) })
}

// cornerEdges selects the three edges meeting at vertex V: the top edge along X, the top edge
// along Y, and the vertical edge — the canonical three-edge corner.
func (d *driver) cornerEdges(e []ref) []ref {
	return filter(e, func(r ref) bool { return isTopX(r) || isTopY(r) || isVert(r) })
}

// twoEdgeL selects the two TOP edges meeting at V (an L), with no vertical edge — a two-edge corner.
func (d *driver) twoEdgeL(e []ref) []ref {
	return filter(e, func(r ref) bool { return isTopX(r) || isTopY(r) })
}

// nearestEdge returns the edge whose midpoint is closest to target — used to grab the new edge
// that appears at the old corner vertex after the first fillet. Nil if there are none.
func nearestEdge(e []ref, target [3]float64) *ref {
	var best *ref
	bestD := 0.0
	for i := range e {
		dx, dy, dz := e[i].p[0]-target[0], e[i].p[1]-target[1], e[i].p[2]-target[2]
		d := dx*dx + dy*dy + dz*dz
		if best == nil || d < bestD {
			best, bestD = &e[i], d
		}
	}
	return best
}

func filter(e []ref, keep func(ref) bool) []ref {
	var out []ref
	for _, r := range e {
		if keep(r) {
			out = append(out, r)
		}
	}
	return out
}

// --- mcp plumbing -----------------------------------------------------------------------------

func (d *driver) call(tool string, a map[string]any) {
	_, _ = d.cs.CallTool(d.ctx, &mcp.CallToolParams{Name: tool, Arguments: a})
}

func (d *driver) callJSON(tool string, a map[string]any, v any) bool {
	res, err := d.cs.CallTool(d.ctx, &mcp.CallToolParams{Name: tool, Arguments: a})
	if err != nil || res.IsError {
		return false
	}
	for _, ct := range res.Content {
		if tc, ok := ct.(*mcp.TextContent); ok {
			return json.Unmarshal([]byte(tc.Text), v) == nil
		}
	}
	return false
}
