// SPDX-License-Identifier: GPL-2.0-only

package bridge

import "oblikovati.org/api/wire"

// The tail_logs tool (a real-time tail of the host operation trace) is generated by mcpgen
// from api/client (Diagnostics.Tail, mcp:tool tail_logs). This file keeps the matching
// MCP *resource* form, which is not method-annotated.

// registerLogsResource serves the recent operation trace as a JSON resource (the full tail).
func (s *Server) registerLogsResource() {
	s.addSchemaResource("oblikovati://logs/recent", "Operation trace",
		"The host's recent operation trace: every served command with timing and outcome, plus "+
			"any structured logs (same data as tail_logs).", wire.MethodLogsTail)
}
