// SPDX-License-Identifier: GPL-2.0-only

package bridge

import (
	"fmt"

	"oblikovati.org/api/wire"
)

// Sketch tool digests — token-efficient one-line summaries for the read-heavy 2D sketch
// enumerations. The tools themselves are generated by mcpgen from the api/client mcp:
// annotations; these summarizers are referenced from there via mcp:digest.

func summarizeSketches(r wire.ListSketchesResult) string {
	items := make([]string, len(r.Sketches))
	for i, sk := range r.Sketches {
		items[i] = fmt.Sprintf("#%d %q on %s (%d entities, DOF %d)", sk.Index, sk.Name, sk.Plane, sk.EntityCount, sk.DOF)
	}
	return countList("sketch", items)
}

func summarizeEntities(r wire.EnumerateEntitiesResult) string {
	items := make([]string, len(r.Entities))
	for i, e := range r.Entities {
		tag := ""
		if e.Construction {
			tag = " (construction)"
		}
		items[i] = fmt.Sprintf("#%d %s id=%d%s", e.Index, e.Kind, e.ID, tag)
	}
	return countList("entity", items)
}

func summarizeConstraints(r wire.ListConstraintsResult) string {
	items := make([]string, len(r.Constraints))
	for i, c := range r.Constraints {
		items[i] = fmt.Sprintf("#%d %s %v", c.Index, c.Kind, c.Entities)
	}
	return countList("constraint", items)
}

func summarizeDimensions(r wire.ListDimensionsResult) string {
	items := make([]string, len(r.Dimensions))
	for i, d := range r.Dimensions {
		driven := ""
		if d.Driven {
			driven = " (driven)"
		}
		items[i] = fmt.Sprintf("#%d %s %s=%s → %.4g%s", d.Index, d.Kind, d.Name, d.Expression, d.Value, driven)
	}
	return countList("dimension", items)
}

func summarizeProfiles(r wire.ListProfilesResult) string {
	items := make([]string, len(r.Profiles))
	for i, p := range r.Profiles {
		state := "open"
		if p.Closed {
			state = "closed"
		}
		items[i] = fmt.Sprintf("#%d %s area=%.4g holes=%d", p.Index, state, p.Area, p.Holes)
	}
	return countList("profile", items)
}
