// SPDX-License-Identifier: GPL-2.0-only

package bridge

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// captureReply is the common shape of every host capture reply (viewport/window):
// the PNG path the host writes plus its pixel dimensions.
type captureReply struct {
	Path   string `json:"path"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}

// addCapture registers an image-returning tool (mcp:image): it forwards the typed
// input In to the host method, waits for the host to write the PNG it names, and
// returns the image (plus a one-line summary) so an MCP client can actually SEE the
// render — the headless equivalent of a screenshot. The host writes the file on a
// later frame, so it appears a beat after the call returns. (capture_viewport,
// capture_window; generated by mcpgen.)
func addCapture[In any](s *Server, name, desc, method string) {
	s.addToolSafe(name, desc, method, func() {
		mcp.AddTool(s.mcp, &mcp.Tool{Name: name, Description: desc},
			func(_ context.Context, _ *mcp.CallToolRequest, in In) (*mcp.CallToolResult, any, error) {
				resp, err := s.callMarshaled(method, in)
				if err != nil {
					return nil, nil, err
				}
				var out captureReply
				if err := json.Unmarshal(resp, &out); err != nil {
					return nil, nil, fmt.Errorf("%s: decode reply: %w", name, err)
				}
				png, err := waitForCapture(out.Path, time.Now())
				if err != nil {
					return nil, nil, fmt.Errorf("%s: %w", name, err)
				}
				return &mcp.CallToolResult{Content: []mcp.Content{
					&mcp.ImageContent{Data: png, MIMEType: "image/png"},
					&mcp.TextContent{Text: fmt.Sprintf("%dx%d captured to %s", out.Width, out.Height, out.Path)},
				}}, json.RawMessage(resp), nil
			})
	})
}

// waitForCapture polls path until the host has written it (its mtime is at or after since — the
// capture is serviced on a later frame than the call), then returns the PNG bytes.
func waitForCapture(path string, since time.Time) ([]byte, error) {
	deadline := since.Add(5 * time.Second)
	for {
		if fi, err := os.Stat(path); err == nil && !fi.ModTime().Before(since) {
			return os.ReadFile(path)
		}
		if time.Now().After(deadline) {
			return nil, fmt.Errorf("the host did not write %s within 5s (is the viewport rendering?)", path)
		}
		time.Sleep(30 * time.Millisecond)
	}
}
